#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : custom_inherit
Version  : 2.4.0
Release  : 18
URL      : https://github.com/rsokl/custom_inherit/archive/v2.4.0/custom_inherit-2.4.0.tar.gz
Source0  : https://github.com/rsokl/custom_inherit/archive/v2.4.0/custom_inherit-2.4.0.tar.gz
Summary  : A Python package that provides customized docstring inheritance       schemes between derived classes and their parents.
Group    : Development/Tools
License  : MIT
Requires: custom_inherit-license = %{version}-%{release}
Requires: custom_inherit-python = %{version}-%{release}
Requires: custom_inherit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# custom_inherit
[![Automated tests status](https://github.com/rsokl/custom_inherit/workflows/Tests/badge.svg)](https://github.com/rsokl/custom_inherit/actions?query=workflow%3ATests+branch%3Amaster)
[![PyPi version](https://img.shields.io/pypi/v/custom_inherit.svg)](https://pypi.python.org/pypi/custom_inherit)
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/custom-inherit.svg)](https://anaconda.org/conda-forge/custom-inherit)
[![Python version support](https://img.shields.io/badge/python-2.7,%20%20%203.4%20%20%20--%203.9-blue.svg)](https://img.shields.io/pypi/v/custom_inherit.svg)

%package license
Summary: license components for the custom_inherit package.
Group: Default

%description license
license components for the custom_inherit package.


%package python
Summary: python components for the custom_inherit package.
Group: Default
Requires: custom_inherit-python3 = %{version}-%{release}

%description python
python components for the custom_inherit package.


%package python3
Summary: python3 components for the custom_inherit package.
Group: Default
Requires: python3-core
Provides: pypi(custom_inherit)

%description python3
python3 components for the custom_inherit package.


%prep
%setup -q -n custom_inherit-2.4.0
cd %{_builddir}/custom_inherit-2.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635716440
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/custom_inherit
cp %{_builddir}/custom_inherit-2.4.0/LICENSE.md %{buildroot}/usr/share/package-licenses/custom_inherit/314cc65c0fdb500e1e69687b7fe732f2a3abee05
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/custom_inherit/314cc65c0fdb500e1e69687b7fe732f2a3abee05

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
