#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : custom_inherit
Version  : 2.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/0e/82/c5bb7ec49a7892a2c583e1017597e3921c59171f10602086ca93c8a83baa/custom_inherit-2.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/0e/82/c5bb7ec49a7892a2c583e1017597e3921c59171f10602086ca93c8a83baa/custom_inherit-2.3.0.tar.gz
Summary  : A Python package that provides customized docstring inheritance       schemes between derived classes and their parents.
Group    : Development/Tools
License  : MIT
Requires: custom_inherit-python = %{version}-%{release}
Requires: custom_inherit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# custom_inherit
[![Build Status](https://travis-ci.com/rsokl/custom_inherit.svg?branch=master)](https://travis-ci.com/rsokl/custom_inherit#)
[![PyPi version](https://img.shields.io/pypi/v/custom_inherit.svg)](https://pypi.python.org/pypi/custom_inherit)
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/custom-inherit.svg)](https://anaconda.org/conda-forge/custom-inherit)
[![Python version support](https://img.shields.io/badge/python-2.7%20%20%203.4%20%203.5%20%203.6%20%203.7%203.8-blue.svg)](https://img.shields.io/pypi/v/custom_inherit.svg)
## Contents
- [Overview](#overview)
- [Basic Usage](#basic-usage)
- [Inheriting Docstrings Using a Metaclass](#inheriting-docstrings-using-a-metaclass)
- [Inheriting Docstrings Using a Decorator](#inheriting-docstrings-using-a-decorator)
- [Advanced Usage (ABCMeta)](#advanced-usage)
- [Built-in Styles](#built-in-styles)
- [Making New Inheritance Styles](#making-new-inheritance-styles)
- [Installation & Getting Started](#installation-and-getting-started)
- [Documentation](#documentation)

%package python
Summary: python components for the custom_inherit package.
Group: Default
Requires: custom_inherit-python3 = %{version}-%{release}

%description python
python components for the custom_inherit package.


%package python3
Summary: python3 components for the custom_inherit package.
Group: Default
Requires: python3-core
Provides: pypi(custom_inherit)

%description python3
python3 components for the custom_inherit package.


%prep
%setup -q -n custom_inherit-2.3.0
cd %{_builddir}/custom_inherit-2.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1597083363
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
