#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : custom_inherit
Version  : 2.2.2
Release  : 9
URL      : https://github.com/rsokl/custom_inherit/archive/v2.2.2.tar.gz
Source0  : https://github.com/rsokl/custom_inherit/archive/v2.2.2.tar.gz
Summary  : A Python package that provides customized docstring inheritance       schemes between derived classes and their parents.
Group    : Development/Tools
License  : MIT
Requires: custom_inherit-license = %{version}-%{release}
Requires: custom_inherit-python = %{version}-%{release}
Requires: custom_inherit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# custom_inherit
[![Build Status](https://travis-ci.com/rsokl/custom_inherit.svg?branch=master)](https://travis-ci.com/rsokl/custom_inherit#)
[![PyPi version](https://img.shields.io/pypi/v/custom_inherit.svg)](https://pypi.python.org/pypi/custom_inherit)
[![Python version support](https://img.shields.io/badge/python-2.7%20%20%203.4%20%203.5%20%203.6%20%203.7%203.8-blue.svg)](https://img.shields.io/pypi/v/custom_inherit.svg)
## Contents
- [Overview](#overview)
- [Basic Usage](#basic-usage)
- [Inheriting Docstrings Using a Metaclass](#inheriting-docstrings-using-a-metaclass)
- [Inheriting Docstrings Using a Decorator](#inheriting-docstrings-using-a-decorator)
- [Advanced Usage (ABCMeta)](#advanced-usage)
- [Built-in Styles](#built-in-styles)
- [Making New Inheritance Styles](#making-new-inheritance-styles)
- [Installation & Getting Started](#installation-and-getting-started)
- [Documentation](#documentation)

%package license
Summary: license components for the custom_inherit package.
Group: Default

%description license
license components for the custom_inherit package.


%package python
Summary: python components for the custom_inherit package.
Group: Default
Requires: custom_inherit-python3 = %{version}-%{release}

%description python
python components for the custom_inherit package.


%package python3
Summary: python3 components for the custom_inherit package.
Group: Default
Requires: python3-core
Provides: pypi(custom_inherit)

%description python3
python3 components for the custom_inherit package.


%prep
%setup -q -n custom_inherit-2.2.2
cd %{_builddir}/custom_inherit-2.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607980446
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/custom_inherit
cp %{_builddir}/custom_inherit-2.2.2/LICENSE.md %{buildroot}/usr/share/package-licenses/custom_inherit/314cc65c0fdb500e1e69687b7fe732f2a3abee05
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/custom_inherit/314cc65c0fdb500e1e69687b7fe732f2a3abee05

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
